### ISSUE TITLE
silk文件转化失败

### ISSUE THREAD

**Issue by multi-cat** [lich0821/SilkMp3Converter#1]
![image](https://github.com/lich0821/SilkMp3Converter/assets/95139167/cd91e49c-4464-4ae2-a6d4-a033857d4296)
当前微信导出来的silk文件开头多了STX字段
![image](https://github.com/lich0821/SilkMp3Converter/assets/95139167/83b56a5d-b86d-4e36-9359-9e04629bc26b)
手动删了之后可以正常转化

**Comment by Cg-Hu** [comment]
不行，我删除了STX字段转换虽然没报错，但是转换出来的mp3格式问价你是损坏的。

**Comment by lich0821** [comment]
[Silk2Mp3](https://github.com/lich0821/WeChatFerry/blob/33071d1f840aa36e0a1a92870befd7ab1163287e/WeChatFerry/spy/funcs.cpp#L289)
